name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
       
      - name: Mostrar entorno
        run: |
          echo "Entorno actual: $NODE_ENV"
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Correr tests
        run: npm test
